baseURL = 'https://rust-atx.org/'
languageCode = 'en-us'
title = 'Rust ATX'
theme = "terminal"

[languages]
  [languages.en]
    title = "Rust ATX"
    subtitle = "Rust ATX"
    keywords = "rust, atx, rustlang, austin, texas"
    copyright = ""

    [languages.en.params.logo]
      logoText = "Rust ATX"
      logoHomeLink = "/"
